apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec:
  replicas: {{ .Values.taskService.replicas }}
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: {{ .Values.taskService.image }}
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PASS
              value: {{ .Values.postgres.password }}
            - name: SECRET_KEY
              value: "supersecretkey"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: NodePort
  selector:
    app: task
  ports:
    - port: {{ .Values.taskService.servicePort }}
      targetPort: 5001
      nodePort: {{ .Values.taskService.nodePort }}